name: Build and Verify SDKs

on:
  push:

jobs:
  build-aars:
    name: Build SDK AARs
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build ExoPlayerAdapter
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: :ExoPlayerAdapter:assemble
    - name: Publish ExoPlayerAdapter to the Dev repo
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: :ExoPlayerAdapter:artifactoryPublish
      env:
        ORG_GRADLE_PROJECT_artifactory_user: ${{ secrets.ARTIFACTORY_EMAIL }}
        ORG_GRADLE_PROJECT_artifactory_password: ${{ secrets.ARTIFACTORY_PASSWORD }}
        GH_USER: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Build MuxExoPlayer
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: :MuxExoPlayer:assemble
    - name: Publish MuxExoPlayer to the Dev repo
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: :MuxExoPlayer:artifactoryPublish
      env:
        ORG_GRADLE_PROJECT_artifactory_user: ${{ secrets.ARTIFACTORY_EMAIL }}
        ORG_GRADLE_PROJECT_artifactory_password: ${{ secrets.ARTIFACTORY_PASSWORD }}
        GH_USER: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # TODO: This isn't enough info for Gradle to reuse anything in subsequent build jobs
    - name: Upload SDK Artifacts
      uses: actions/upload-artifact@v2
      with:
        path: | 
          MuxExoPlayer/buildout/outputs/**
          ExoPlayerAdapter/buildout/outputs/**
        
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: build-aars

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Download SDK Binaries
      uses: actions/download-artifact@v2
      with:
        path: | 
          MuxExoPlayer/buildout/outputs/**
          ExoPlayerAdapter/buildout/outputs/**
    - name: Unit Test ExoPlayerAdapter
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: :ExoPlayerAdapter:test
    - name: Unit Test MuxExoPlayer
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: :MuxExoPlayer:test
  
  verify-demo:
    name: Verify the Demo build
    runs-on: ubuntu-latest
    needs: build-aars

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Download SDK Binaries
      uses: actions/download-artifact@v2
      with:
        path: | 
          MuxExoPlayer/buildout/outputs/**
          ExoPlayerAdapter/buildout/outputs/**
    - name: Verify Demo Build
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: :demo:assemble
